# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:-UseContainerSupport
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
android.enableOnDemandConfiguration=true

# 代理配置（沙箱环境）
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
